title: Mobile Apps
email: samuel_grunebaum@horacemann.org
description: >-
  This is the class website for Mobile Apps.
#Site settings
excerpt_length: 55

include: ['units']

#Build settings
markdown: kramdown
permalink: pretty
future: true
